spring:
  application:
    name: eventreminder

  datasource:
    url: jdbc:postgresql://localhost:5432/events
    username: root
    password: root

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/events
    user: root
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false